services:

  space-travel:
    container_name: space-travel-api-dev
    image: node:18-alpine
    restart: "no"
    ports:
      - "8082:8082"
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      PORT: 8082
      MONGODB_CRED: mongodb://root:example@mongodb:27017/
    command: /bin/sh -c "npm i && npm run test"

  mongodb:
    image: mongo
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    logging:
      driver: none
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/    
